import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist } from "next/font/google";
import "./globals.css";



const helveticaNow = localFont({
  src: [
    {
      path: "../../public/fonts/helvetica-now/HelveticaNow-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-now/HelveticaNow-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-now/HelveticaNow-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-now",
  display: "swap",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Omnistra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${helveticaNow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
